d = dialog('Position',[300 300 250 150],'Name','My Dialog');

txt = uicontrol('Parent',d,...
                'Style','text',...
                'Position',[20 80 210 40],...
                'String','Importing Signal Sample');
count = 0;

while(~isfile('../Runtime/sample.mat'))
    pause(0.5);
    if count == 15
        break
    elseif (mod(count, 3) == 0)
        txt = uicontrol('Parent',d,...
                        'Style','text',...
                        'Position',[20 80 210 40],...
                        'String','Importing Signal Sample.');
        count = count + 1;
    elseif (mod(count, 3) == 1)
        txt = uicontrol('Parent',d,...
                        'Style','text',...
                        'Position',[20 80 210 40],...
                        'String','Importing Signal Sample..');
        count = count + 1;            
    elseif (mod(count, 3) == 2)

        txt = uicontrol('Parent',d,...
                        'Style','text',...
                        'Position',[20 80 210 40],...
                        'String','Importing Signal Sample...');
        count = count + 1;            
    end
end
delete(d)
clear('d')
load('..\Runtime\sample.mat')
